### PR TITLE
AUS-2748: upgrade spring-platform-bom to 2.0.8, increase portal-core version to 1.7.0

### PR DESCRIPTION
**Pull request by yan073**

### CODE REVIEW

**Comment by joshvote** [comment]
Just going to hold off on pulling this right now, Carsten has identified that we need further testing against ANVGL

**Comment by yan073** [comment]
Sure. No problem. Thank you for letting me know.

The first build of portal core failed due to taking too long to download updated dependency components.
The second build succeeded with the cached dependencies.

The travis build for portal still fails due to missing portal-core version 1.7.0. I am not sue how and when the new version (1.7.0) of portal-core will be deployed to our maven repository.

Cheers,
Bo

**Comment by fcarsten** [comment]
Sorry for the delay. Can’t reproduce the problems I had some weeks ago when trying this (with 2.0.7 though). Happy to be merged into master.

c

**Comment by yan073** [comment]
Rollback the version change of portal-core. It is not a big change

**Pull request closed without merging**
